version: "3.8"
services:
  arma:
    build: .
    ports:
      - "3000:3000"  
    volumes:
      - ./:/app  
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./
          target: ./
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
